server:
  port: ${PORT}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret-key: ${SECRET_KEY}
  access-exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}

cool-sms:
  api-key: ${COOL_SMS_API_KEY}
  secret-key: ${COOL_SMS_SECRET_KEY}
  from: ${COOL_SMS_FROM}